---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.19.2
  kernelspec:
    display_name: venv (3.12.3.final.0)
    language: python
    name: python3
---

<!-- #region editable=true slideshow={"slide_type": ""} -->
# Counterfeit detection
<!-- #endregion -->

The task in this assignment is to detect the  counterfeit banknotes. The data set is based on [banknote authentication Data Set ](https://archive.ics.uci.edu/ml/datasets/banknote+authentication#) from UCI Machine Learning repository. The first three columns denote different parameters obtained from the photographs of the banknotes and last colum provides the label. Frankly as the dataset does not have any description I don't know  which labels corresponds to real and which to counterfeited banknotes. let's assume that label one (positive) denotes the clounterfeits. The set  [banknote_authentication.csv](./data/banknote_authentication.csv) can be found in the `data`  directory.

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
import  matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(8,8)
```

Please insert you  firstname  and name below

```{python}
print("Jakub Budzyński")
from  sklearn.model_selection import train_test_split
seed = 31287
data = pd.read_csv('data/banknotes_data.csv')
```

```{python}
data.head()
```

```{python tags=c("skip")}
data.describe()
```

```{python tags=c("skip")}
data.info()
```

```{python}
data_train, data_test = train_test_split(data, test_size=0.2, shuffle=True, stratify=data.loc[:,'counterfeit'], random_state=seed)
```

```{python}
data_train
```

```{python}
lbls_train = data_train['counterfeit']
lbls_test = data_test['counterfeit']
```

```{python}
fig, ax = plt.subplots(1,4, figsize=(22,5))
for i in range(4):
    ax[i].hist(data_train[lbls_train==0].iloc[:,i], bins=32, histtype='step', color='blue')
    ax[i].hist(data_train[lbls_train==1].iloc[:,i], bins=32, histtype='step', color='red')
    ax[i].hist(data_train[lbls_train==0].iloc[:,i], bins=32, histtype='bar', color='lightblue', alpha=0.25)
    ax[i].hist(data_train[lbls_train==1].iloc[:,i], bins=32, histtype='bar', color='orange', alpha =0.25)
```

<!-- #region editable=true slideshow={"slide_type": ""} -->
# Problem 1
<!-- #endregion -->

<!-- #region editable=true slideshow={"slide_type": ""} -->
Train a neural network classifier to predict counterfeit banknotes. Use the features `a0` and `a3`. Calculate the confussion matrix  and AUC score. 
<!-- #endregion -->

```{python editable=TRUE, slideshow={'slide_type': ''}}
import torch
import torch.nn as nn
features= [0, 3] #choose features
nf=len(features) # 2
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
# training

features_train = torch.from_numpy(data_train.values[:,features]).to(dtype=torch.float32)
labels_train = torch.from_numpy(data_train.values[:,4:5]).to(dtype=torch.float32) #selecting only column 4, but keepong it in 2D structure.
print(labels_train[:10]) #so its only matching values like "0" and "1"
print(features_train[:10]) #just passing a0 and a3 feature

# test 
features_test = torch.from_numpy(data_test.values[:,features]).to(dtype=torch.float32)
labels_test = torch.from_numpy(data_test.values[:,4:5]).to(dtype=torch.float32)
print(labels_test[:10]) #so its only matching values like "0" and "1"
print(features_test[:10])
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
# in_features (int) – size of each input sample
# out_features (int) – size of each output sample

model = nn.Sequential(
    nn.Linear(in_features=nf, out_features=16),
    nn.ReLU(),

    nn.Linear(in_features=16, out_features=8),
    nn.ReLU(),

    nn.Linear(in_features=8, out_features=1),
    nn.Sigmoid()
)

#3 layer network 2->16->8->1
loss_fn = nn.BCELoss() #Creates a criterion that measures the Binary Cross Entropy between the target and the input probabilities - Pytorch doc
optimizer = torch.optim.SGD(model.parameters(),lr=0.001)
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
from sklearn.metrics import roc_curve, confusion_matrix, accuracy_score
y_true = labels_test.numpy()
print(y_true[:5])
print()

with torch.no_grad(): #random weights use
  y_proba = model(features_test)
  y_predicted = 1*(y_proba>0.5) # converts booleans into integers.

accuracy_score(y_true, y_pred=y_predicted)

# 0.91 > 0.5 → True
# 0.12 > 0.5 → False

# True behaves like 1
# False behaves like 0
```

```{python editable=TRUE, slideshow={'slide_type': ''}}


for era in range(20):
    for epoch in range(500):
        optimizer.zero_grad()
        pred = model(features_train)
        # print(f"pred: {pred.shape}")
        # print(f"pred: {pred[0][0]}")
        # print(f"pred: {pred[0]}")
        # print(f"pred: {pred[:10]}")
        # print()
        # print(f"labels: {labels_train}")
        loss = loss_fn(pred, labels_train) #how well or how bad network performs
        loss.backward()
        optimizer.step()
    with torch.no_grad():
        pred =  model(features_train)
        acc_train =  torch.mean(0.0+ ((pred > 0.5)== (labels_train>0.5)))
        pred =  model(features_test)
        acc_test =  torch.mean(0.0+ ((pred > 0.5)== (labels_test>0.5)))
    
    print(f"acc_train: {acc_train.item():.4f}, acc_test: {acc_test.item():.4f}")


'''
nn.Sequential(
    nn.Linear(2,16),
    nn.ReLU(),
    nn.Linear(16,8),
    nn.ReLU(),
    nn.Linear(8,2),
    nn.Sigmoid()
)
'''

# 87% is ok but it could be better
```

```{python}
features= [0,1,2, 3] #checking how network would perform with all features
nf=len(features) # 4



features_train = torch.from_numpy(data_train.values[:,features]).to(dtype=torch.float32)
labels_train = torch.from_numpy(data_train.values[:,4:5]).to(dtype=torch.float32) #selecting only column 4, but keepong it in 2D structure.


features_test = torch.from_numpy(data_test.values[:,features]).to(dtype=torch.float32)
labels_test = torch.from_numpy(data_test.values[:,4:5]).to(dtype=torch.float32)

print("showing that I use other examples for training and other examples for test")
print(len(labels_train))
print(len(labels_test))

# other neural network
model = nn.Sequential(
    nn.Linear(in_features=nf, out_features=8),
    nn.ReLU(),

    nn.Linear(in_features=8, out_features=16),
    nn.ReLU(),

    nn.Linear(in_features=16, out_features=8),
    nn.ReLU(),

    nn.Linear(in_features=8, out_features=1),
    nn.Sigmoid()

)

optimizer = torch.optim.SGD(model.parameters(),lr=0.001)

with torch.no_grad(): #random weights use
  y_proba = model(features_test)
  y_predicted = 1*(y_proba>0.5)


for era in range(20):
    for epoch in range(500):
        optimizer.zero_grad()
        pred = model(features_train)
        # print(f"pred: {pred.shape}")
        # print(f"pred: {pred[0][0]}")
        # print(f"pred: {pred[0]}")
        # print(f"pred: {pred[:10]}")
        # print()
        # print(f"labels: {labels_train}")
        loss = loss_fn(pred, labels_train) #how well or how bad network performs
        loss.backward()
        optimizer.step()
    with torch.no_grad():
        pred =  model(features_train)
        acc_train =  torch.mean(0.0+ ((pred > 0.5)== (labels_train>0.5)))
        pred =  model(features_test)
        acc_test =  torch.mean(0.0+ ((pred > 0.5)== (labels_test>0.5)))
    
    print(f"acc_train: {acc_train.item():.4f}, acc_test: {acc_test.item():.4f}")

```
